import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import TagButton from "~/components/tagButton";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from abc" });
  const { data: getAll, isLoading } = api.image.getAll.useQuery();
  console.log(getAll);

  if (isLoading) return <div>Loading...</div>;
  if (!getAll) return <div>Something went wrong</div>;

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  // const urlTest: string = getAll[0]?.body;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#090016] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-1 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            ai<span className="text-[hsl(194,62%,58%)]">.avid</span> prompts
          </h1>
          <div className="flex gap-2 md:gap-4">
            <TagButton />
            <TagButton />
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>

          <div className="flex-start mt-8 flex justify-center flex-row flex-wrap">
            {getAll.map((p) => {
              return (
                <div
                  className="w-4/12 md:w-3/12 lg:w-1/5"
                  key={p.seq}
                >
                  <img src={p.imgurl} className="aspect-[3/4] object-cover p-1"/>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
